service: aws-node-express-dynamodb-api

frameworkVersion: '2'

custom:
  dynamodb:
    start:
      migrate: true
    stages:
      - dev
  peopleTable: 'person-${self:provider.stage}'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ PeopleTable, Arn ]
  environment:
    PEOPLE_TABLE: ${self:custom.peopleTable}

functions:
  api:
    handler: api/people.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

resources:
  Resources:
    PeopleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: cpf
            AttributeType: S
          - AttributeName: next_shot_date
            AttributeType: S
          - AttributeName: name
            AttributeType: S
          - AttributeName: phone_number
            AttributeType: S
          - AttributeName: last_shot_date
            AttributeType: S
          - AttributeName: vaccine
            AttributeType: S
          - AttributeName: status
            AttributeType: S

        KeySchema:
          - AttributeName: cpf
            KeyType: HASH
          - AttributeName: next_shot_date
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.peopleTable}


plugins:
  - serverless-dynamodb-local
  - serverless-offline
